on:
  push:
    paths:
    - 'docs/**'
    - '**.yml'
    branches:
    - master

jobs: 
  build: 
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2

    - name: Build docs
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Install dependencies 
      run: | 
        python -m pip install --upgrade pip 
        pip install mkdocs-material 

    - name: Build and push
      run: |
        git config user.name ${{ secrets.GH_USER }}
        git config user.email "${{ secrets.GH_MAIL }}"
        git remote add gh-token "https://${{ secrets.GH_TOKEN}}@github.com/:user/:repo.git"
        git fetch gh-token && git fetch gh-token gh-pages:gh-pages
        python -m mkdocs gh-deploy -v --clean --remote-name gh-token
        git push gh-token gh-pages


        