on:
  push:
    paths:
    - 'docs/**'
    - '**.yml'
    branches:
    - master

jobs: 
  build: 
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2

    - name: Build docs
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Install dependencies 
      run: | 
        python -m pip install --upgrade pip 
        pip install mkdocs-material 

    - name: Build and push
      run: |
        mkdocs gh-deploy --force


        


        